/*
 * main program for testing ssd1306_i2c.c
 */

#include "sdkconfig.h" // generated by "make menuconfig"

#if CONFIG_SSD1306_I2C_MAIN_ENABLED

#include "driver/gpio.h"
#include "esp_err.h"
#include "esp_log.h"

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "ssd1306_i2c.h"

#define TAG "ssd1306_i2c_main"

#define POWER_VEXT_PIN    21
#define POWER_VEXT_ON     0

void display_thread(void* param)
{
    ESP_LOGI(TAG, "Creating display");

    display_t *display = ssd1306_i2c_create(DISPLAY_FLAGS_DEFAULT);

    ESP_LOGI(TAG, "Display created, calling write_text");

    display->set_xy(display, 3, 3);

    for (int offset = 0; offset < 20; ++offset) {
        display->clear(display);
        display->set_xy(display, offset, offset);
        display->write_text(display, "Hello, world!\n");
        vTaskDelay(pdMS_TO_TICKS(10));
    }

    ESP_LOGI(TAG, "Text writting: reading back x/y");

    int x;
    int y;
    display->get_xy(display, &x, &y);

    ESP_LOGI(TAG, "ssd1306 display x %d y %d", x, y);

    vTaskDelete(NULL);
}

void app_main(void)
{
    gpio_config_t power = {
        .intr_type = GPIO_PIN_INTR_DISABLE,
        .mode = GPIO_MODE_OUTPUT,
        .pin_bit_mask = 1ULL << POWER_VEXT_PIN,
        .pull_down_en = 0,
        .pull_up_en = GPIO_PULLUP_DISABLE,
    };

    ESP_ERROR_CHECK(gpio_config(&power));

    gpio_set_level(POWER_VEXT_PIN, POWER_VEXT_ON);
    vTaskDelay(pdMS_TO_TICKS(100));

	xTaskCreate(display_thread, "display_thread",  16384, NULL, 6, NULL);
}

#endif /* CONFIG_SSD1306_I2C_MAIN_ENABLED */
